set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(FRAMELAB_MINGW_TRIPLE "x86_64-w64-mingw32" CACHE STRING "MinGW-w64 compiler prefix")

find_program(CMAKE_C_COMPILER NAMES ${FRAMELAB_MINGW_TRIPLE}-gcc REQUIRED)
find_program(CMAKE_RC_COMPILER NAMES ${FRAMELAB_MINGW_TRIPLE}-windres REQUIRED)
find_program(CMAKE_AR NAMES ${FRAMELAB_MINGW_TRIPLE}-ar)
find_program(CMAKE_RANLIB NAMES ${FRAMELAB_MINGW_TRIPLE}-ranlib)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
